### ISSUE TITLE
Test failures on fresh checkout

### ISSUE THREAD

**Issue by GeorgSchneider** [finos/legend-engine#1096]
## Support Question

I'm trying to build `legend-engine` on a fresh checkout from `master`, and getting some test failures when running `mvn install` (see [attached logs](https://github.com/finos/legend-engine/files/9927715/legend-engine-mvn-install.txt)). Could you let me know if these are "expected" or why they are occuring? They seem like genuine assertion failures.

I'm running this in WSL (Ubuntu 18.04.1 LTS) on Windows:
```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/apache-maven-3.8.6
Java version: 11.0.14, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.10.102.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"
```

**Comment by finos-admin** [comment]
This issue was closed because it has been inactive for 35 days. Please re-open if this issue is still relevant.
