### ISSUE TITLE
Switch the default config file to use the GitlabClient instead of the KerberosClient

### ISSUE THREAD

**Issue by epsstan** [finos/legend-engine#169]
## Feature Request
Switch the default config file to use the GitlabClient instead of the KerberosClient.

### Description of Problem:
The userTestConfig.json[1] that we refer to in our install guides, uses the LocalKerberosClient.  This is not useful to users on personal devices who do not have a local Kerberos installation. 

[1] https://github.com/finos/legend-engine/blob/master/legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig.json

### Potential Solutions:
Include a config file that uses the GitlabClient instead of the KerberosClient.

Also, update the installer guides to use the new config file.

**Comment by akphi** [comment]
Fixed in https://github.com/finos/legend-engine/pull/171
