### ISSUE TITLE
Image won't run by itself

### ISSUE THREAD

**Issue by pedroleaoc** [finos/legend-engine#299]
Hi folks, 
I am working on a [Charmed Operator](juju.is/docs/sdk) for Legend Server and I am trying to understand how the different parts of Legend interact during deployment.  

Should I be able to simply `pull` and `run` the Engine image directly from dockerhub? 

It seems like it's trying to access a volume that is not yet mounted. I know these images were probably design to work with Docker Compose mainly, but am I missing something obvious here (that is probably covered by the Maven install guide)? 

Thanks :-)

``` 
$ docker pull finos/legend-engine-server:2.35.1
$ docker run --rm -it finos/legend-engine-server:2.35.1
15:26:30.336 [main] INFO Alloy Execution Server - {"duration":0.0,"eventType":"URL_FACTORY_REGISTERED","message":"Registered Alloy URL Factory","timeStamp":"2021-07-02 15:26:30.037","user":"_UNKNOWN_"}
log4j:WARN No appenders could be found for logger (org.jboss.logging).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.io.FileNotFoundException: File /config/config.json not found
        at io.dropwizard.configuration.FileConfigurationSourceProvider.open(FileConfigurationSourceProvider.java:18)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:80)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at org.finos.legend.engine.server.Server.main(Server.java:91)
```

**Comment by akphi** [comment]
@pedroleaoc Did you provide a config file when you try to run this?

**Comment by pedroleaoc** [comment]
Thanks for your answer, @akphi. 

What I've done so far:
* Populated `./config.properties` with sensible information
* `./scripts/setup.sh ./config.properties`
   This creates a tree of directories which I mapped in my `docker run` command. Something like this:
```
docker run -t -i \
 -v $BUILD_DIR/ssl:/ssl \
 -v $BUILD_DIR/generated-configs/engine:/config \
 -v $BUILD_DIR/generated-configs/gitlab:/gitlab-config \
 -v $BUILD_DIR/scripts:/scripts \
 -v $BUILD_DIR/templates/engine:/templates \
finos/legend-engine-server:2.35.1
```
* Pushed a `config.json` file inside the `/engine` directory. 
Question:
Where is `config.json` created? I found a [generic one](https://github.com/finos/legend/blob/15c9c27763b2f8e4bffee1a7ca08a9d7e1820997/installers/aws-docker/install/templates/engine/config.json) and removed everything related to Mongo - is there a better way to generate/get this file?

* The container runs and the service responds to my attempts to connect (by failing)- which is expected since my `config.json` is a hack. 

Question: Can I run engine without sdlc? Does it make sense Legend-wise?

**Comment by akphi** [comment]
@pedroleaoc Ah I think I see your problem now. The `Dockerfile` for `legend-engine` is like this https://github.com/finos/legend-engine/blob/333214b2a439ae751e9caea9035d90958a9d1ab2/legend-engine-server/Dockerfile#L15-L17

The last line, it was looking for the config at the location `config/config.json`.  So you might want to modify your mounted drive to something like 

```bash
-v $BUILD_DIR/generated-configs/engine/config:/config \
```

Or something along that line, the best way to check is to go inside the container and make sure the path `/config/config.json` exists.

>   Where is `config.json` created? I found a [generic one](https://github.com/finos/legend/blob/15c9c27763b2f8e4bffee1a7ca08a9d7e1820997/installers/aws-docker/install/templates/engine/config.json) and removed everything related to Mongo - is there a better way to generate/get this file?

We have mentioned in our [installation guide](https://legend.finos.org/docs/installation/maven-install-guide) that if you don't go the `docker-compose` route, you can use [this config](https://github.com/finos/legend-engine/blob/master/legend-engine-server/src/test/resources/org/finos/legend/engine/server/test/userTestConfig.json)



> Question: Can I run engine without sdlc? Does it make sense Legend-wise?

Yes, in our stack we make sure `engine` does not depend on `sdlc`.

**Comment by pedroleaoc** [comment]
Ah! Thanks for the pointers, that helped a lot!

I was looking for the (wrong) config file in the wrong place.
