### ISSUE TITLE
Empty test data for services with multi connection runtimes causes build failures

### ISSUE THREAD

**Issue by gs-ssh16** [finos/legend-engine#430]
### Steps to Reproduce:
Define a service with a multi connection runtime

### Expected Result:
Ideally, the CI build should pass without any error. Empty test data should be assigned for each connection

### Actual Result:
CI build fails with json deserialisation exception

**Comment by hardikmaheshwari** [comment]
This should be handled with testable flow (Commit https://github.com/finos/legend-engine/commit/de6392aeb51044198a7874a8c3dd9e2130768912 )
