### ISSUE TITLE
Wrong class leverage to validate partition fields

### ISSUE THREAD

**Issue by rafaelbey** [finos/legend-engine#644]
During multi flat target part validation, the partition fields are validated against the top level model class rather than against the flat part class (thru the modelProperty)

https://github.com/finos/legend-engine/blob/dfa4e98ddf8c4128ee6a746e5e5727fe100512c9/legend-engine-language-pure-dsl-persistence/src/main/java/org/finos/legend/engine/language/pure/dsl/persistence/compiler/toPureGraph/HelperPersistenceBuilder.java#L387-L398

The class from targetType should have been pass instead of modelClass.

```java
._partitionFields(ListIterate.collect(part.partitionFields, p -> validateAndResolvePropertyName((Class) targetType, p, part.sourceInformation, context)))
```

**Comment by davidsunglee** [comment]
Same problem exists with deduplication strategy validation. Both should be fixed.
